import { TimelineEvent } from './timeline-event';
import { Company } from './company';
import { TrialCaseFolder } from './trial-case-folder';
import { DocumentFolder } from './document-folder';
import { TrialCaseNarrativeStoryItem } from './trial-case-narrative-story-item';
import { TimelineEventNote } from './timeline-event-note';
import { UserComment } from './user-comment';
import { TrialCase } from './trial-case';
import { TrialCaseCard } from './trial-case-card';
import { UserActivity } from './user-activity';
import { TrialCasePerson } from './trial-case-person';
import { TrialCaseNarrativeStory } from './trial-case-narrative-story';
import { TrialCaseSection } from './trial-case-section';
import { TrialCaseCardNote } from './trial-case-card-note';
import { BaseTrackEntity } from './base-track-entity';
import { TrialCaseSubsection } from './trial-case-subsection';
import { TrialCaseTask } from './trial-case-task';
import { UserTrialCaseFavorite } from './user-trial-case-favorite';
import { TrialCaseNotebookSection } from './trial-case-notebook-section';
import { TrialCaseUserRole } from './trial-case-user-role';
import { TrialCaseFolderUserRole } from './trial-case-folder-user-role';

export interface User extends BaseTrackEntity {
  id: string;
  name: string;
  title: string;
  avatar: string | null;
  phone: string | null;
  email: string | null;
  description: string | null;
  companyId: string | null;
  company: Company | null;
  createdCards: TrialCaseCard[];
  deletedCards: TrialCaseCard[];
  createdCardsNotes: TrialCaseCardNote[];
  deletedCardsNotes: TrialCaseCardNote[];
  cardTasks: TrialCaseTask[];
  deletedCaseNarrativeStories: TrialCaseNarrativeStory[];
  createdTimeLineEventNotes: TimelineEventNote[];
  deletedTimeLineEventNotes: TimelineEventNote[];
  createdCases: TrialCase[] | null;
  deletedCases: TrialCase[];
  companies: Company[];
  createdFiles: File[];
  deletedFiles: File[];
  applicationUserActivities: UserActivity[];
  comments: UserComment[];
  createdTimelineEvents: TimelineEvent[];
  deletedTimelineEvents: TimelineEvent[];
  createdCaseNarrativeStories: TrialCaseNarrativeStory[];
  assignedCardTasks: TrialCaseTask[];
  modifiedCases: TrialCase[];
  modifiedCompanies: Company[];
  deletedCompanies: Company[];
  modifiedFiles: File[];
  modifiedTimelineEvents: TimelineEvent[];
  modifiedTimeLineEventNotes: TimelineEventNote[];
  modifiedCards: TrialCaseCard[];
  modifiedCardsNotes: TrialCaseCardNote[];
  createdTrialCaseFolders: TrialCaseFolder[];
  modifiedTrialCaseFolders: TrialCaseFolder[];
  deletedTrialCaseFolders: TrialCaseFolder[];
  createdTrialCasePersons: TrialCasePerson[];
  modifiedTrialCasePersons: TrialCasePerson[];
  deletedTrialCasePersons: TrialCasePerson[];
  createdTrialCaseSections: TrialCaseSection[];
  modifiedTrialCaseSections: TrialCaseSection[];
  deletedTrialCaseSections: TrialCaseSection[];
  createdTrialCaseSubsections: TrialCaseSubsection[];
  modifiedTrialCaseSubsections: TrialCaseSubsection[];
  deletedTrialCaseSubsections: TrialCaseSubsection[];
  modifiedUsers: User[];
  deletedUsers: User[];
  userTrialCaseFavorites: UserTrialCaseFavorite[];
  createdFileDocumentFolders: DocumentFolder[];
  modifiedCardTasks: TrialCaseTask[];
  deletedCardTasks: TrialCaseTask[];
  modifiedCaseNarrativeStories: TrialCaseNarrativeStory[];
  createdUsers: User[];
  modifiedFileDocumentFolders: DocumentFolder[];
  deletedFileDocumentFolders: DocumentFolder[];
  createdTrialCaseNotebookSections: TrialCaseNotebookSection[];
  modifiedTrialCaseNotebookSections: TrialCaseNotebookSection[];
  deletedTrialCaseNotebookSections: TrialCaseNotebookSection[];
  createdFileDocuments: Document[];
  modifiedFileDocuments: Document[];
  deletedFileDocuments: Document[];
  createdTrialCaseNarrativeStoryItems: TrialCaseNarrativeStoryItem[];
  modifiedTrialCaseNarrativeStoryItems: TrialCaseNarrativeStoryItem[];
  deletedTrialCaseNarrativeStoryItems: TrialCaseNarrativeStoryItem[];
  trialCaseUserRoles: TrialCaseUserRole[];
  trialCaseFolderUserRoles: TrialCaseFolderUserRole[];
}
